version: '3.8'

services:
  gateway:
    build: ./backend/gateway
    ports:
      - "5001:8000"
    depends_on:
      - market-service
      - news-service
      - portfolio-service
      - ai-service
    networks:
      - moneymitra-net

  market-service:
    build: ./backend/market-service
    networks:
      - moneymitra-net

  news-service:
    build: ./backend/news-service
    env_file:
      - ./backend/.env
    networks:
      - moneymitra-net

  portfolio-service:
    build: ./backend/portfolio-service
    networks:
      - moneymitra-net

  ai-service:
    build: ./backend/ai-service
    env_file:
      - ./backend/.env
    networks:
      - moneymitra-net

  frontend:
    build:
      context: .
      args:
        VITE_API_URL: http://localhost:5001
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - gateway
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "18080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - moneymitra-net
    environment:
      - JAVA_OPTS=-Xmx512m

  sonarqube:
    image: sonarqube:community
    ports:
      - "19000:9000"
    networks:
      - moneymitra-net
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db

  db:
    image: postgres:12
    networks:
      - moneymitra-net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - moneymitra-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - moneymitra-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - moneymitra-net

networks:
  moneymitra-net:
    driver: bridge

volumes:
  jenkins_home:
  postgres_data:
