global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'
    metrics_path: '/prometheus/'
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'moneymitra-gateway'
    static_configs:
      - targets: ['gateway:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
