controller:
  serviceType: NodePort
  nodePort: 30003
  admin:
    username: admin
    password: admin123
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - sonar
persistence:
  enabled: true
  size: 8Gi
  storageClass: standard
