service:
  type: NodePort
  nodePort: 30002
persistence:
  enabled: true
  size: 5Gi
  storageClass: standard
postgresql:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: standard

monitoringPasscode: "admin123"
community:
  enabled: true
initSysctl:
  enabled: false